name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-compose-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and run containers
        run: |
          docker-compose up --build -d
          echo "⏳ Waiting for services to become healthy..."
          sleep 15

      - name: Test service1 route through NGINX
        run: |
          for i in {1..5}; do
            curl --fail http://localhost:8080/service1 && break
            echo "Retrying service1..."
            sleep 5
          done

      - name: Test service2 route through NGINX
        run: |
          for i in {1..5}; do
            curl --fail http://localhost:8080/service2 && break
            echo "Retrying service2..."
            sleep 5
          done

      - name: Shutdown containers
        if: always()
        run: docker-compose down
